### PR TITLE
feat: adding --title with custom formatting

### PR DESCRIPTION
**Pull request by mazunki**
i was working on something where it would have been useful to specify a custom titles for my window, but found no way of doing this from within wl-mirror itself.

the current default behaviour remains the same, but one can now specify a custom title, including specifiers for custom variables.

re the code itself: beware that the string manipulation code isn't super pretty, but gets the job done. hopefully there's no off-by-one errors there. please let me know if there's something i should change or do differently.

### CODE REVIEW

**Comment by Ferdi265** [comment]
This looks cool! Thank you for the contribution!

I think I would probably want the string manipulation code to be written with as few instances of alloc(manually calculated length) + copy(hopefully fits else gets truncated) as possible, which is why I prefer APIs similar to asprintf, but it's really hard to do this justice in C, and from a quick glance reading this on my phone what you did looks quite good :)

I think I'll just branch off from your code and change a few things, and then merge that.

**Comment by mazunki** [comment]
yep, the code looks uglier than it could have looked because I measured the length before allocating it, and keep track of not overshooting it as i go. i was thinking of hard-coding a statically-sized array and number length, but figured i may as well make it withstand the weather.

yippie on merge :) once fixed version is out, i'll bump the ebuild for gentoo while at it

**Comment by Ferdi265** [comment]
> yep, the code looks uglier than it could have looked because I measured the length before allocating it, and keep track of not overshooting it as i go. i was thinking of hard-coding a statically-sized array and number length, but figured i may as well make it withstand the weather.
> 
> yippie on merge :) once fixed version is out, i'll bump the ebuild for gentoo while at it

great!

**Comment by Ferdi265** [comment]
Hi! I just started reading through the code properly and I think I'll need some time integrating this.

I don't like the fact that the code uses `snprintf(_, _, non-literal-format-string, _)` since it causes warnings with strict format string security warnings enabled (`-Wformat=2`), so I will try to rewrite it in a way that doesn't have that.

Otherwise, I really like the syntax! I also like that you already added documentation (save for the man page, but I will also add it to that)

**Comment by Ferdi265** [comment]
Since I just refactored a lot of the wl-mirror codebase I tried rebasing your branch onto the new wl-mirror codebase and apparently this seems to have closed the PR.

**Comment by Ferdi265** [comment]
Merged into main as of 55ef61f with d88fbdb as a fixup commit on top. Sorry it took so long to merge and had this hiccup.

**Comment by mazunki** [comment]
Don't worry about attribution, as long as the feature works I'm happy about it! :)

Thanks for merging!

**Comment by Ferdi265** [comment]
> Don't worry about attribution, as long as the feature works I'm happy about it! :)
> 
> Thanks for merging!
> 
> PS: Are we looking at a new version release soon?

Hi! I completely forgot about this; Yes, a new release is gonna be out soon.

Since I merged another PR with a bugfix recently and completely forgot about this, I think I'm gonna release these two as v0.17.0 and postpone XDG portals to v0.18.0

**Pull request closed without merging**
