### PR TITLE
Add support for fullscreen and fullscreen-output flags

### PR DESCRIPTION
**Pull request by SoumyaRanjanPatnaik**
Add `--fullscreen` and `--fullscreen-output` flags to start `wl-mirror` in fullscreen. Addresses #30. Copying over the implementation checklist from https://github.com/Ferdi265/wl-mirror/issues/30#issuecomment-1845189624. 

Checklist:

- [x] Implement --fullscreen in wl-mirror
- [x] Implement --fullscreen-output in wl-mirror
- [ ] Implement fullscreen command in wl-present
- [ ] Implement fullscreen-output command in wl-present
- [ ] Document --fullscreen in man pages
- [ ] Document --fullscreen-output in man pages
- [ ] Document --fullscreen in README
- [ ] Document --fullscreen-output in README

### CODE REVIEW

**Comment by Ferdi265** [comment]
Hi! Thanks for the PR. I currently have a lot of things to do over christmas, so I probably do not have time to merge your PR over the holidays, but I will try to get to it as soon as I can.

**Comment by Ferdi265** [comment]
Hi! I managed to get to this now. Your changes are great, but I did some more debugging and added some additional useful features. My state is in branch [feature-fullscreen](https://github.com/Ferdi265/wl-mirror/tree/feature-fullscreen).

This is the current checklist state:
- [X] Implement --fullscreen in wl-mirror
- [X] Implement --fullscreen-output in wl-mirror
- [ ] Implement fullscreen command in wl-present
- [ ] Implement fullscreen-output command in wl-present
- [X] Document --fullscreen in man pages
- [X] Document --fullscreen-output in man pages
- [X] Document --fullscreen in README
- [X] Document --fullscreen-output in README

I will likely merge my extended version of this in the next few days, feel free to add onto it if you have any ideas or comments.

**Comment by Ferdi265** [comment]
merged into next

**Comment by SoumyaRanjanPatnaik** [comment]
I just saw this. The changes you made were well thought out.  Happy to see this in the latest release. Merry Christmas and a happy new year :)

**Pull request merged**
